### ISSUE TITLE
OpenCVForUnity version

### ISSUE THREAD

**Issue by Juh-yun** [EnoxSoftware/MarkerLessARExample#11]
Hello!
I got a lot of error messages when using MarkerLessARExample.
...
The type or namespace name 'CoreModule' does not exist in the namespace 'OpenCVForUnity'
The type or namespace name 'Mat' could not be found
...
Is there a set OpenCV version of OpenCVforUnity when using MarkerLessARExample?
Now I am using OpenCV 3.2.
Or is there some other reason for the error?

![image](https://user-images.githubusercontent.com/78392509/196104021-43a4a6e8-0728-43da-8dba-671059f86d55.png)

**Comment by EnoxSoftware** [comment]
MaekerBasedARExample requires OpenCVForUntiy2.4.2 or later.
